- name: Install Docker from Official Repo and Deploy Container
  hosts: all
  become: true
  tasks:
    - name: Remove old Docker and containerd packages
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - containerd.io
          - runc
        state: absent
      ignore_errors: true

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
        state: present

    - name: Update apt cache after adding Docker repo
      apt:
        update_cache: yes

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Run Docker container
      docker_container:
        name: banking
        image: aksh193/banking:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
