- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove containerd if it exists (conflicts with containerd.io)
      apt:
        name: containerd
        state: absent
      ignore_errors: yes

    - name: Remove containerd.io if already partially installed
      apt:
        name: containerd.io
        state: absent
      ignore_errors: yes

    - name: Fix broken install
      apt:
        fix_broken: yes

    - name: Autoremove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean up apt cache
      apt:
        autoclean: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: true

    - name: Deploy Docker Container
      docker_container:
        name: banking
        image: aksh193/banking:1.0
        state: started
        restart_policy: always
        published_ports:
          - "8084:8081"
